//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMain.EFDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long Id { get; set; }
        public long AdderId { get; set; }
        public long InvitedId { get; set; }
        public System.DateTimeOffset SendingDate { get; set; }
        public int RelationTypeId { get; set; }
        public Nullable<System.DateTimeOffset> LastChangeDate { get; set; }
        public long ConversationId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
        public virtual Conversation Conversation { get; set; }
    }
}
