//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMain.EFDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationReply
    {
        public long Id { get; set; }
        public long AuthorId { get; set; }
        public long ConversationId { get; set; }
        public string Body { get; set; }
        public System.DateTimeOffset SendingTime { get; set; }
        public bool IsDeleted { get; set; }
        public int ConversationReplyStatusId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Conversation Conversation { get; set; }
        public virtual ConversationReplyStatus ConversationReplyStatus { get; set; }
        public virtual User UserReceiver { get; set; }
    }
}
